// USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// UI REDUCER TYPES

export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//DATA REDUCER TYPES
export const SET_JOBS = "SET_JOBS";
export const GET_POSTS = "GET_POSTS";

export const JOBS_LOADING = "JOBS_LOADING";
export const POST_POST = "POST_POST";
export const DELETE_POST = "DELETE_POST";
